### ISSUE TITLE
Default answer isn't working

### ISSUE THREAD

**Issue by tiagokrebs** [aziontech/azion#666]
Hey guys, for the third question below the default answer is not being treated.  
When seeing `(y\N)` on the end of a terminal question is expected that the upper case letter is the default one, and so if the user just hits return then that should be the response.  

The other thing I notice is the forward-slash `(y\N)` instead of a slash `(y/N)`, which is more common. A little bit of IMO.

<img width="765" alt="image" src="https://github.com/aziontech/azion/assets/55988677/a824d667-9e0e-4636-8aff-d5e66c3be73b">

**Comment by maxwelbm** [comment]
https://github.com/aziontech/azion/pull/670 @tiagokrebs by default if you press enter it understands as no this was added in the latest version

**Comment by PatrickMenoti** [comment]
Resolved in the latest deploy
