### ISSUE TITLE
Múltiplo aceite de envio das métricas

### ISSUE THREAD

**Issue by maxwelbm** [aziontech/azion#698]
Problem:

A pergunta de confirmação de envio das métricas da CLI para a Azion parece estar sendo mostrada ao cliente mais vezes do que o esperado:

![image](https://github.com/aziontech/azion/assets/52722027/67b5f855-356d-4dad-9bba-42def8ac4d0c)

Expected Behavior:

Essa pergunta deve ser feita ao usuário apenas 1x, e nunca mais.

Step by Step to Reproduce:

```
azion init --config --help
```

**Comment by PatrickMenoti** [comment]
Why is `--help` not taking priority over` --config`? 🤔

**Comment by maxwelbm** [comment]
It is taking a parameter and using the `--help`  value as the path to a new con

**Comment by maxwelbm** [comment]
I'm going to apply two solutions, validate the path and check that it has the prefix -- and copy the authorization config from metrics 🔨
